default_platform(:android)

platform :android do

  desc "Build and distribute Debug and Release APKs to Firebase"

  lane :distribute do |options|

    flavor = options[:flavor]

    UI.user_error!("Flavor is required") if flavor.nil? || flavor.empty?

    flavor = flavor.downcase

    UI.message("Selected flavor: #{flavor}")

    distribute_apk(
      flavor: flavor,
      build_type: "Debug"
    )

    distribute_apk(
      flavor: flavor,
      build_type: "Release"
    )
  end


private_lane :distribute_apk do |options|

  flavor = options[:flavor]
  build_type = options[:build_type]

  task = "assemble#{flavor.capitalize}#{build_type}"

  UI.message("Building #{task}")

  gradle(
    task: task
  )

  apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

  UI.user_error!(
    "APK not found for #{flavor} #{build_type}"
  ) unless apk_path && File.exist?(apk_path)

  UI.success("APK generated: #{apk_path}")

  firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    apk_path: apk_path,
    android_artifact_type: "APK",
    service_credentials_file: "firebase-service-account.json",
    groups: "qa-testers",
    release_notes: "#{flavor.upcase} #{build_type} build"
  )
end

end